expect.exist       <- \(component) component |> is.null() |> expect_equal(FALSE)
expect.equal       <- \(actual, expected) actual |> expect_equal(expected)
expect.list        <- \(members) members |> is.list() |> expect_equal(TRUE)
expect.empty       <- \(entities) entities |> nrow() |> expect_equal(0)
expect.no.error    <- \(result) result |> expect_no_error()
expect.error       <- \(result, error) result |> expect_error(error)
expect.contain     <- \(entities, entity) entities[entities[['Id']] == entity[['Id']],] |> nrow() |> expect_equal(1)
expect.not.contain <- \(entities, entity) entities[entities[['Id']] == entity[['Id']],] |> nrow() |> expect_equal(0)
expect.equal.data <- \(actual, expected) actual |> all.equal(expected, check.attributes = FALSE) |> isTRUE() |> expect_equal(TRUE)