name: build_Docker_image

env:
  # github.repository as IMAGE_NAME VARIABLE
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

  #defines when the workflow is triggered
on:
  push:
    branches: ['main']
    # Publish semver tags as releases.
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    #checkout registry

    steps:
      #accessing the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      #Docker container builder
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # to push the container image, workflow has to authenticate to the github registry
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          #store password and username in GitHub secrets and reference it.
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # Build and push docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}         
             #   cache-from: type=gha
